FROM busybox

WORKDIR /tmp

RUN mkdir -p /tmp/learningBase/train \
    -p /tmp/learningBase/validation

COPY data/training_data.csv /tmp/learningBase/train/
COPY data/test_data.csv     /tmp/learningBase/validation/
COPY images/learningBase_life_style_death/Readme.md /tmp/learningBase/Readme.md

CMD ["sh"]