#ARM64 (aarch64) variant. Runs on Apple Silicon or other ARM hosts.
#builds and pushes codeBase for aarch64 as codebase_life_style_death_aarch64.
version: "3.9"
services:
  knowledge_base:
    image: moazemad/knowledgebase_life_style_death_x86_64
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/knowledgeBase/ && cp -r /knowledgeBase/ /tmp/;
  learning_base:
    image: moazemad/learningbase_life_style_death_x86_64
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/learningBase/ && cp -r /learningBase/ /tmp/;
  activation_base:
    image: moazemad/activationbase_life_style_death_x86_64
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/acGvaGonBase/ && cp -r /acGvaGonBase/ /tmp/;
  code_base:
    user: root
    image: moazemad/codebase_life_style_death_aarch64
    volumes:
      - ai_system:/tmp
    depends_on:
      - knowledge_base
      - activation_base
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/acGvaGonBase/ && cp -r /acGvaGonBase/ /tmp/;
        python3 /app/codeBase/run_inference.py
volumes:
  ai_system:
    external: true
