# syntax=docker/dockerfile:1
FROM busybox
RUN mkdir -p /acGvaGonBase
COPY data/activation_data.csv /acGvaGonBase/activation_data.csv
COPY images/activationBase_Life-Style-Death_x86_64/README.md /README.md