FROM busybox

WORKDIR /tmp

RUN mkdir -p /tmp/activationBase

COPY data/activation_data.csv /tmp/activationBase/
COPY images/activationBase_life_style_death/Readme.md /tmp/activationBase/Readme.md

CMD ["sh"]